version: '3.3'
services:
  mqtt:
    image: eclipse/mosquitto:1.4.8
    container_name: mqtt
    restart: always
    volumes:
      - /root/mosquitto/config:/mosquitto/config
      - /root/mosquitto/data:/mosquitto/data
      - /root/mosquitto/log:/mosquitto/log 
    ports:
      - 1883:1883
      - 9001:9001
